### PR TITLE
Fix/main page snax

### LINKED ISSUE #21: Prettify error handling on Main
Use snackbar rather than alerts

### PR DESCRIPTION
**Pull request by rkarim0598**
Fixes #21 , also contains bonus fix of event swiping

### CODE REVIEW

File: app/src/views/Main.vue [hunk 1]
```diff
@@ -295,18 +310,21 @@ export default {
...
-          console.log(error);
-          alert("Something went wrong, please refresh");
+          this.handleError(error);
         }
       } else {
         console.log("just passing for now");
       }
 
-      console.log(this.recs[this.event_id][0]);
+      // apparently has to be done this way for Vue to react to nested stuff
```
Comment (johnameyer) [inline app/src/views/Main.vue:320]: Probably since object comparison is done on the instance https://vuejs.org/v2/guide/reactivity.html#For-Objects
